### ISSUE TITLE
Bug url_escape::encode_fragment

### ISSUE THREAD

**Issue by ahtremblay** [magiclen/url-escape#2]
The following code

`url_escape::encode_fragment("http://example.org?a=1");`

returns 

`"http://example.org?a=1"`

It does not encode it as a fragment. It in fact does nothing.

The correct result should be `http%3A%2F%2Fexample.org%3Fa%3D1`

**Comment by magiclen** [comment]
According to the [spec](https://url.spec.whatwg.org/#fragment-percent-encode-set), the fragment percent-encode set is the C0 control percent-encode set and U+0020 SPACE, U+0022 ("), U+003C (<), U+003E (>), and U+0060 (`).

If you want to encode `:`, `/`, `?` and `=`, you should use the `encode_component` function or the `encode_userinfo` function.
